-- XorWoW TCG: the card items, their drops and the card table the worldserver reads
-- (src/server/scripts/Custom/xorwow_tcg.cpp). GENERATED by scripts/client-patch/build_tcg.py
-- from client-patch/tcg/cards.json in the XorWoW repo: edit that and rebuild. Idempotent.
--
-- Card N is item 261000+N: a copy of the Hearthstone (class 15) that is not bound, stacks to 20
-- and is used up by its spell 261000 ("add to the collection", the Spell/Item.dbc rows come from
-- the client patch). Quality follows the tier: 1-2 white, 3-4 green, 5-6 blue, 7-8 purple, 9-10 orange.

CREATE TABLE IF NOT EXISTS `xorwow_tcg_card` (
    `id` TINYINT UNSIGNED NOT NULL,
    `name` VARCHAR(64) NOT NULL,
    `item` INT UNSIGNED NOT NULL,
    `creature` INT UNSIGNED NOT NULL,
    `tier` TINYINT UNSIGNED NOT NULL,
    `era` TINYINT UNSIGNED NOT NULL COMMENT '0 classic, 1 tbc, 2 wotlk: a card counts once its expansion is open',
    `top` TINYINT UNSIGNED NOT NULL,
    `right` TINYINT UNSIGNED NOT NULL,
    `bottom` TINYINT UNSIGNED NOT NULL,
    `left` TINYINT UNSIGNED NOT NULL,
    `element` TINYINT UNSIGNED NOT NULL COMMENT '0 none, 1 Water 2 Fire 3 Frost 4 Earth 5 Arcane 6 Holy 7 Shadow 8 Nature (the circle order)',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
DELETE FROM `xorwow_tcg_card`;
INSERT INTO `xorwow_tcg_card` (`id`, `name`, `item`, `creature`, `tier`, `era`, `top`, `right`, `bottom`, `left`, `element`) VALUES
(1, 'Lake Thresher', 261001, 14357, 1, 0, 3, 5, 2, 1, 1),
(2, 'Deepstrider Giant', 261002, 4686, 2, 0, 5, 3, 2, 5, 4),
(3, 'King Bangalash', 261003, 731, 3, 0, 7, 1, 5, 3, 0),
(4, 'Devilsaur', 261004, 6498, 4, 0, 4, 6, 2, 7, 0),
(5, 'Aku''mai', 261005, 4829, 5, 0, 7, 6, 5, 3, 1),
(6, 'Mother Smolderweb', 261006, 10596, 6, 0, 1, 8, 8, 3, 8),
(7, 'Princess Theradras', 261007, 12201, 7, 0, 5, 6, 6, 8, 4),
(8, 'Azuregos', 261008, 6109, 8, 0, 6, 7, 4, 9, 3),
(9, 'Magmadar', 261009, 11982, 9, 0, 7, 4, 6, 10, 2),
(10, 'Ragnaros', 261010, 11502, 10, 0, 6, 9, 10, 4, 2),
(11, 'Kresh', 261011, 3653, 1, 0, 6, 1, 1, 2, 1),
(12, 'Lupine Horror', 261012, 3863, 1, 0, 2, 1, 4, 4, 7),
(13, 'Agam''ar', 261013, 4511, 1, 0, 1, 5, 4, 1, 0),
(14, 'Mechano-Tank', 261014, 6225, 1, 0, 5, 1, 1, 3, 0),
(15, 'Shrike Bat', 261015, 4861, 2, 0, 3, 2, 1, 7, 0),
(16, 'Jadespine Basilisk', 261016, 4863, 2, 0, 6, 1, 4, 3, 4),
(17, 'Boneflayer Ghoul', 261017, 7347, 2, 0, 5, 2, 5, 2, 7),
(18, 'Skeletal Frostweaver', 261018, 7341, 2, 0, 5, 1, 3, 5, 3),
(19, 'Sul''lithuz Sandcrawler', 261019, 8095, 3, 0, 6, 2, 6, 3, 4),
(20, 'Constrictor Vine', 261020, 12220, 3, 0, 7, 5, 1, 3, 8),
(21, 'Deep Lurker', 261021, 8384, 3, 0, 4, 4, 7, 2, 1),
(22, 'Stone Steward', 261022, 4860, 3, 0, 6, 6, 3, 2, 6),
(23, 'Warpwood Crusher', 261023, 13021, 4, 0, 4, 5, 5, 6, 8),
(24, 'Crypt Beast', 261024, 10413, 4, 0, 3, 7, 3, 6, 7),
(25, 'Rockwing Gargoyle', 261025, 10408, 4, 0, 6, 2, 7, 3, 7),
(26, 'Risen Construct', 261026, 10488, 4, 0, 1, 6, 4, 7, 3),
(27, 'Agathelos the Raging', 261027, 4422, 5, 0, 7, 2, 7, 4, 2),
(28, 'Crowd Pummeler 9-60', 261028, 6229, 5, 0, 6, 6, 2, 7, 0),
(29, 'Bloodmage Thalnos', 261029, 4543, 5, 0, 3, 6, 5, 7, 2),
(30, 'Lord Vyletongue', 261030, 12236, 5, 0, 7, 7, 4, 2, 7),
(31, 'Shade of Eranikus', 261031, 5709, 6, 0, 1, 8, 4, 8, 8),
(32, 'Lord Roccor', 261032, 9025, 6, 0, 6, 5, 8, 4, 4),
(33, 'Ironaya', 261033, 7228, 6, 0, 7, 2, 8, 5, 6),
(34, 'Pyroguard Emberseer', 261034, 9816, 6, 0, 8, 2, 8, 2, 2),
(35, 'General Drakkisath', 261035, 10363, 7, 0, 6, 8, 4, 7, 2),
(36, 'Magmus', 261036, 9938, 7, 0, 8, 6, 7, 3, 2),
(37, 'Baroness Anastari', 261037, 10436, 7, 0, 8, 5, 2, 8, 7),
(38, 'Kirtonos the Herald', 261038, 10506, 7, 0, 5, 7, 8, 5, 7),
(39, 'Ysondre', 261039, 14887, 8, 0, 9, 6, 2, 8, 8),
(40, 'Emeriss', 261040, 14889, 8, 0, 3, 7, 9, 6, 7),
(41, 'Gyth', 261041, 10339, 8, 0, 5, 1, 9, 9, 2),
(42, 'Kurinnaxx', 261042, 15348, 8, 0, 9, 5, 2, 9, 4),
(43, 'Chromaggus', 261043, 14020, 9, 0, 10, 8, 2, 6, 5),
(44, 'Ossirian the Unscarred', 261044, 15339, 9, 0, 3, 1, 10, 10, 4),
(45, 'Princess Huhuran', 261045, 15509, 9, 0, 8, 10, 3, 5, 8),
(46, 'Hakkar', 261046, 14834, 9, 0, 7, 10, 1, 7, 7),
(47, 'Nefarian', 261047, 11583, 10, 0, 10, 10, 3, 3, 7),
(48, 'C''Thun', 261048, 15727, 10, 0, 10, 4, 6, 9, 7),
(49, 'Ouro', 261049, 15517, 10, 0, 10, 8, 6, 4, 4),
(50, 'Vaelastrasz the Corrupt', 261050, 13020, 10, 0, 5, 10, 3, 9, 2),
(51, 'Raging Colossus', 261051, 19188, 1, 1, 2, 1, 6, 1, 4),
(52, 'Felguard Destroyer', 261052, 18977, 1, 1, 1, 4, 1, 5, 7),
(53, 'Gutripper', 261053, 18257, 1, 1, 2, 3, 1, 5, 0),
(54, 'Bladespire Ravager', 261054, 20729, 2, 1, 7, 1, 3, 1, 0),
(55, 'Farahlon Giant', 261055, 18885, 2, 1, 5, 2, 5, 3, 4),
(56, 'Deathskitter', 261056, 18647, 2, 1, 3, 4, 5, 3, 8),
(57, 'Fulgorge', 261057, 18678, 3, 1, 3, 6, 4, 4, 4),
(58, 'Goretooth', 261058, 17144, 3, 1, 6, 3, 1, 6, 1),
(59, 'Nuramoc', 261059, 20932, 3, 1, 7, 2, 3, 5, 8),
(60, 'Hemathion', 261060, 18692, 4, 1, 7, 4, 4, 4, 5),
(61, 'Voidhunter Yar', 261061, 18683, 4, 1, 2, 3, 6, 7, 7),
(62, 'Terokkarantula', 261062, 20682, 4, 1, 2, 7, 6, 3, 8),
(63, 'Ghaz''an', 261063, 18105, 5, 1, 6, 5, 6, 5, 1),
(64, 'Broggok', 261064, 17380, 5, 1, 3, 10, 2, 1, 8),
(65, 'Pandemonius', 261065, 18341, 5, 1, 5, 3, 7, 6, 7),
(66, 'Murmur', 261066, 18708, 6, 1, 7, 8, 3, 4, 5),
(67, 'Warp Splinter', 261067, 17977, 6, 1, 4, 8, 5, 6, 8),
(68, 'Anzu', 261068, 23035, 6, 1, 2, 8, 8, 4, 7),
(69, 'Aeonus', 261069, 17881, 7, 1, 8, 3, 5, 8, 5),
(70, 'Harbinger Skyriss', 261070, 20912, 7, 1, 1, 8, 7, 7, 5),
(71, 'Vexallus', 261071, 24744, 7, 1, 8, 8, 5, 4, 5),
(72, 'Doomwalker', 261072, 17711, 8, 1, 9, 4, 8, 4, 4),
(73, 'Nightbane', 261073, 17225, 8, 1, 4, 4, 8, 9, 7),
(74, 'Maiden of Virtue', 261074, 16457, 8, 1, 8, 9, 6, 2, 6),
(75, 'Magtheridon', 261075, 17257, 9, 1, 5, 10, 8, 3, 2),
(76, 'Void Reaver', 261076, 19516, 9, 1, 7, 2, 7, 10, 5),
(77, 'Doom Lord Kazzak', 261077, 18728, 9, 1, 10, 1, 7, 7, 7),
(78, 'Illidan Stormrage', 261078, 22917, 10, 1, 6, 7, 6, 10, 7),
(79, 'Archimonde', 261079, 17968, 10, 1, 10, 7, 2, 8, 2),
(80, 'Kil''jaeden', 261080, 25315, 10, 1, 8, 5, 10, 6, 7),
(81, 'Dreadtalon', 261081, 26838, 1, 2, 2, 1, 2, 6, 0),
(82, 'Hulking Jormungar', 261082, 26293, 1, 2, 1, 3, 3, 5, 4),
(83, 'Scion of Quetz''lun', 261083, 28477, 1, 2, 4, 2, 4, 3, 8),
(84, 'Iron Sentinel', 261084, 29984, 2, 2, 6, 2, 2, 3, 4),
(85, 'Terror Spinner', 261085, 32475, 2, 2, 5, 3, 3, 4, 8),
(86, 'Guardian of Zim''Rhuk', 261086, 28597, 2, 2, 4, 4, 5, 2, 6),
(87, 'Icehorn', 261087, 32361, 3, 2, 3, 5, 5, 5, 3),
(88, 'Loque''nahak', 261088, 32517, 3, 2, 5, 6, 3, 3, 5),
(89, 'Reanimated Frost Wyrm', 261089, 26841, 3, 2, 5, 6, 2, 4, 3),
(90, 'Gondria', 261090, 33776, 4, 2, 7, 3, 1, 6, 3),
(91, 'Arcturis', 261091, 38453, 4, 2, 7, 5, 4, 3, 8),
(92, 'Storm Giant', 261092, 24812, 4, 2, 6, 5, 4, 5, 8),
(93, 'Krik''thir the Gatewatcher', 261093, 28684, 5, 2, 5, 5, 7, 4, 8),
(94, 'King Dred', 261094, 27483, 5, 2, 4, 6, 7, 4, 0),
(95, 'Krystallus', 261095, 27977, 5, 2, 6, 2, 6, 7, 4),
(96, 'Hadronox', 261096, 28921, 6, 2, 4, 8, 7, 3, 8),
(97, 'Keristrasza', 261097, 26723, 6, 2, 7, 5, 8, 1, 3),
(98, 'Volkhan', 261098, 28587, 6, 2, 6, 8, 4, 5, 2),
(99, 'Anub''arak', 261099, 29120, 7, 2, 8, 8, 4, 4, 7),
(100, 'Ley-Guardian Eregos', 261100, 27656, 7, 2, 7, 7, 2, 8, 5),
(101, 'Loken', 261101, 28923, 7, 2, 8, 4, 4, 8, 6),
(102, 'Archavon the Stone Watcher', 261102, 31125, 8, 2, 9, 3, 9, 2, 4),
(103, 'Razorscale', 261103, 33186, 8, 2, 9, 6, 7, 3, 2),
(104, 'Patchwerk', 261104, 16028, 8, 2, 2, 9, 9, 4, 0),
(105, 'Sapphiron', 261105, 15989, 9, 2, 4, 4, 9, 10, 3),
(106, 'Malygos', 261106, 28859, 9, 2, 8, 4, 10, 4, 5),
(107, 'Sindragosa', 261107, 36853, 9, 2, 9, 10, 4, 2, 3),
(108, 'The Lich King', 261108, 36597, 10, 2, 2, 6, 9, 10, 3),
(109, 'Yogg-Saron', 261109, 33288, 10, 2, 9, 6, 10, 2, 7),
(110, 'Kel''Thuzad', 261110, 15990, 10, 2, 4, 10, 2, 10, 3);

DELETE FROM `item_template` WHERE `entry` BETWEEN 261001 AND 261999;
DELETE FROM `item_template_locale` WHERE `ID` BETWEEN 261001 AND 261999;
DROP TEMPORARY TABLE IF EXISTS `xorwow_tcg_item`;
CREATE TEMPORARY TABLE `xorwow_tcg_item` SELECT * FROM `item_template` WHERE `entry` = 6948;
UPDATE `xorwow_tcg_item` SET `entry` = 261001, `name` = 'Lake Thresher Card', `displayid` = 261001, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1, Water.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261002, `name` = 'Deepstrider Giant Card', `displayid` = 261002, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261003, `name` = 'King Bangalash Card', `displayid` = 261003, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261004, `name` = 'Devilsaur Card', `displayid` = 261004, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261005, `name` = 'Aku''mai Card', `displayid` = 261005, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Water.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261006, `name` = 'Mother Smolderweb Card', `displayid` = 261006, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261007, `name` = 'Princess Theradras Card', `displayid` = 261007, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261008, `name` = 'Azuregos Card', `displayid` = 261008, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261009, `name` = 'Magmadar Card', `displayid` = 261009, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261010, `name` = 'Ragnaros Card', `displayid` = 261010, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261011, `name` = 'Kresh Card', `displayid` = 261011, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1, Water.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261012, `name` = 'Lupine Horror Card', `displayid` = 261012, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261013, `name` = 'Agam''ar Card', `displayid` = 261013, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261014, `name` = 'Mechano-Tank Card', `displayid` = 261014, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261015, `name` = 'Shrike Bat Card', `displayid` = 261015, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261016, `name` = 'Jadespine Basilisk Card', `displayid` = 261016, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261017, `name` = 'Boneflayer Ghoul Card', `displayid` = 261017, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261018, `name` = 'Skeletal Frostweaver Card', `displayid` = 261018, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261019, `name` = 'Sul''lithuz Sandcrawler Card', `displayid` = 261019, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261020, `name` = 'Constrictor Vine Card', `displayid` = 261020, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261021, `name` = 'Deep Lurker Card', `displayid` = 261021, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Water.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261022, `name` = 'Stone Steward Card', `displayid` = 261022, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Holy.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261023, `name` = 'Warpwood Crusher Card', `displayid` = 261023, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261024, `name` = 'Crypt Beast Card', `displayid` = 261024, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261025, `name` = 'Rockwing Gargoyle Card', `displayid` = 261025, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261026, `name` = 'Risen Construct Card', `displayid` = 261026, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261027, `name` = 'Agathelos the Raging Card', `displayid` = 261027, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261028, `name` = 'Crowd Pummeler 9-60 Card', `displayid` = 261028, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261029, `name` = 'Bloodmage Thalnos Card', `displayid` = 261029, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261030, `name` = 'Lord Vyletongue Card', `displayid` = 261030, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261031, `name` = 'Shade of Eranikus Card', `displayid` = 261031, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261032, `name` = 'Lord Roccor Card', `displayid` = 261032, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261033, `name` = 'Ironaya Card', `displayid` = 261033, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Holy.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261034, `name` = 'Pyroguard Emberseer Card', `displayid` = 261034, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261035, `name` = 'General Drakkisath Card', `displayid` = 261035, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261036, `name` = 'Magmus Card', `displayid` = 261036, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261037, `name` = 'Baroness Anastari Card', `displayid` = 261037, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261038, `name` = 'Kirtonos the Herald Card', `displayid` = 261038, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261039, `name` = 'Ysondre Card', `displayid` = 261039, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261040, `name` = 'Emeriss Card', `displayid` = 261040, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261041, `name` = 'Gyth Card', `displayid` = 261041, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261042, `name` = 'Kurinnaxx Card', `displayid` = 261042, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261043, `name` = 'Chromaggus Card', `displayid` = 261043, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261044, `name` = 'Ossirian the Unscarred Card', `displayid` = 261044, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261045, `name` = 'Princess Huhuran Card', `displayid` = 261045, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261046, `name` = 'Hakkar Card', `displayid` = 261046, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261047, `name` = 'Nefarian Card', `displayid` = 261047, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261048, `name` = 'C''Thun Card', `displayid` = 261048, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261049, `name` = 'Ouro Card', `displayid` = 261049, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261050, `name` = 'Vaelastrasz the Corrupt Card', `displayid` = 261050, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261051, `name` = 'Raging Colossus Card', `displayid` = 261051, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261052, `name` = 'Felguard Destroyer Card', `displayid` = 261052, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261053, `name` = 'Gutripper Card', `displayid` = 261053, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261054, `name` = 'Bladespire Ravager Card', `displayid` = 261054, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261055, `name` = 'Farahlon Giant Card', `displayid` = 261055, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261056, `name` = 'Deathskitter Card', `displayid` = 261056, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261057, `name` = 'Fulgorge Card', `displayid` = 261057, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261058, `name` = 'Goretooth Card', `displayid` = 261058, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Water.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261059, `name` = 'Nuramoc Card', `displayid` = 261059, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261060, `name` = 'Hemathion Card', `displayid` = 261060, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261061, `name` = 'Voidhunter Yar Card', `displayid` = 261061, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261062, `name` = 'Terokkarantula Card', `displayid` = 261062, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261063, `name` = 'Ghaz''an Card', `displayid` = 261063, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Water.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261064, `name` = 'Broggok Card', `displayid` = 261064, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261065, `name` = 'Pandemonius Card', `displayid` = 261065, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261066, `name` = 'Murmur Card', `displayid` = 261066, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261067, `name` = 'Warp Splinter Card', `displayid` = 261067, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261068, `name` = 'Anzu Card', `displayid` = 261068, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261069, `name` = 'Aeonus Card', `displayid` = 261069, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261070, `name` = 'Harbinger Skyriss Card', `displayid` = 261070, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261071, `name` = 'Vexallus Card', `displayid` = 261071, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261072, `name` = 'Doomwalker Card', `displayid` = 261072, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261073, `name` = 'Nightbane Card', `displayid` = 261073, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261074, `name` = 'Maiden of Virtue Card', `displayid` = 261074, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Holy.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261075, `name` = 'Magtheridon Card', `displayid` = 261075, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261076, `name` = 'Void Reaver Card', `displayid` = 261076, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261077, `name` = 'Doom Lord Kazzak Card', `displayid` = 261077, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261078, `name` = 'Illidan Stormrage Card', `displayid` = 261078, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261079, `name` = 'Archimonde Card', `displayid` = 261079, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261080, `name` = 'Kil''jaeden Card', `displayid` = 261080, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261081, `name` = 'Dreadtalon Card', `displayid` = 261081, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261082, `name` = 'Hulking Jormungar Card', `displayid` = 261082, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261083, `name` = 'Scion of Quetz''lun Card', `displayid` = 261083, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 1, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261084, `name` = 'Iron Sentinel Card', `displayid` = 261084, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261085, `name` = 'Terror Spinner Card', `displayid` = 261085, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261086, `name` = 'Guardian of Zim''Rhuk Card', `displayid` = 261086, `Quality` = 1, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 2, Holy.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261087, `name` = 'Icehorn Card', `displayid` = 261087, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261088, `name` = 'Loque''nahak Card', `displayid` = 261088, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261089, `name` = 'Reanimated Frost Wyrm Card', `displayid` = 261089, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 3, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261090, `name` = 'Gondria Card', `displayid` = 261090, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261091, `name` = 'Arcturis Card', `displayid` = 261091, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261092, `name` = 'Storm Giant Card', `displayid` = 261092, `Quality` = 2, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 4, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261093, `name` = 'Krik''thir the Gatewatcher Card', `displayid` = 261093, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261094, `name` = 'King Dred Card', `displayid` = 261094, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261095, `name` = 'Krystallus Card', `displayid` = 261095, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 5, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261096, `name` = 'Hadronox Card', `displayid` = 261096, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Nature.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261097, `name` = 'Keristrasza Card', `displayid` = 261097, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261098, `name` = 'Volkhan Card', `displayid` = 261098, `Quality` = 3, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 6, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261099, `name` = 'Anub''arak Card', `displayid` = 261099, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261100, `name` = 'Ley-Guardian Eregos Card', `displayid` = 261100, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261101, `name` = 'Loken Card', `displayid` = 261101, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 7, Holy.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261102, `name` = 'Archavon the Stone Watcher Card', `displayid` = 261102, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Earth.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261103, `name` = 'Razorscale Card', `displayid` = 261103, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8, Fire.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261104, `name` = 'Patchwerk Card', `displayid` = 261104, `Quality` = 4, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 8.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261105, `name` = 'Sapphiron Card', `displayid` = 261105, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261106, `name` = 'Malygos Card', `displayid` = 261106, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Arcane.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261107, `name` = 'Sindragosa Card', `displayid` = 261107, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 9, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261108, `name` = 'The Lich King Card', `displayid` = 261108, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261109, `name` = 'Yogg-Saron Card', `displayid` = 261109, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Shadow.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
UPDATE `xorwow_tcg_item` SET `entry` = 261110, `name` = 'Kel''Thuzad Card', `displayid` = 261110, `Quality` = 5, `Flags` = 0, `bonding` = 0, `maxcount` = 0, `stackable` = 20, `BuyCount` = 1, `BuyPrice` = 0, `SellPrice` = 0, `ItemLevel` = 1, `RequiredLevel` = 0, `spellid_1` = 261000, `spelltrigger_1` = 0, `spellcharges_1` = -1, `spellcooldown_1` = -1, `spellcategory_1` = 0, `spellcategorycooldown_1` = -1, `description` = 'XorWoW TCG card, tier 10, Frost.', `ScriptName` = '';
INSERT INTO `item_template` SELECT * FROM `xorwow_tcg_item`;
DROP TEMPORARY TABLE `xorwow_tcg_item`;

-- the use spell: xorwow_tcg.cpp adds the card to the account (the item is used up by its charge)
DELETE FROM `spell_script_names` WHERE `spell_id` = 261000;
INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES (261000, 'spell_xorwow_tcg_card');

-- Drops: each card from its creature and the creature's heroic / 25-man versions. A creature
-- without loot (a chest boss like Malygos, a few elites) gets a loot table of its own.
DROP TEMPORARY TABLE IF EXISTS `xorwow_tcg_drop_base`;
DROP TEMPORARY TABLE IF EXISTS `xorwow_tcg_drop`;
CREATE TEMPORARY TABLE `xorwow_tcg_drop_base` (`creature` INT UNSIGNED NOT NULL, `item` INT UNSIGNED NOT NULL, `chance` FLOAT NOT NULL);
INSERT INTO `xorwow_tcg_drop_base` (`creature`, `item`, `chance`) VALUES
(14357, 261001, 25.0),
(4686, 261002, 25.0),
(731, 261003, 25.0),
(6498, 261004, 1.0),
(4829, 261005, 12.0),
(10596, 261006, 10.0),
(12201, 261007, 8.0),
(6109, 261008, 20.0),
(11982, 261009, 8.0),
(11502, 261010, 6.0),
(3653, 261011, 25.0),
(3863, 261012, 2.0),
(4511, 261013, 2.0),
(6225, 261014, 2.0),
(4861, 261015, 1.5),
(4863, 261016, 1.5),
(7347, 261017, 1.5),
(7341, 261018, 1.5),
(8095, 261019, 1.2),
(12220, 261020, 1.2),
(8384, 261021, 1.2),
(4860, 261022, 1.2),
(13021, 261023, 1.0),
(10413, 261024, 1.0),
(10408, 261025, 1.0),
(10488, 261026, 1.0),
(4422, 261027, 12.0),
(6229, 261028, 12.0),
(4543, 261029, 12.0),
(12236, 261030, 12.0),
(5709, 261031, 10.0),
(9025, 261032, 10.0),
(7228, 261033, 10.0),
(9816, 261034, 10.0),
(10363, 261035, 8.0),
(9938, 261036, 8.0),
(10436, 261037, 8.0),
(10506, 261038, 8.0),
(14887, 261039, 20.0),
(14889, 261040, 20.0),
(10339, 261041, 8.0),
(15348, 261042, 10.0),
(14020, 261043, 8.0),
(15339, 261044, 8.0),
(15509, 261045, 8.0),
(14834, 261046, 8.0),
(11583, 261047, 6.0),
(15727, 261048, 6.0),
(15517, 261049, 6.0),
(13020, 261050, 6.0),
(19188, 261051, 2.0),
(18977, 261052, 2.0),
(18257, 261053, 25.0),
(20729, 261054, 1.5),
(18885, 261055, 1.5),
(18647, 261056, 25.0),
(18678, 261057, 25.0),
(17144, 261058, 25.0),
(20932, 261059, 25.0),
(18692, 261060, 25.0),
(18683, 261061, 25.0),
(20682, 261062, 25.0),
(18105, 261063, 12.0),
(17380, 261064, 12.0),
(18341, 261065, 12.0),
(18708, 261066, 10.0),
(17977, 261067, 10.0),
(23035, 261068, 10.0),
(17881, 261069, 8.0),
(20912, 261070, 8.0),
(24744, 261071, 8.0),
(17711, 261072, 20.0),
(17225, 261073, 10.0),
(16457, 261074, 10.0),
(17257, 261075, 8.0),
(19516, 261076, 8.0),
(18728, 261077, 20.0),
(22917, 261078, 6.0),
(17968, 261079, 6.0),
(25315, 261080, 6.0),
(26838, 261081, 25.0),
(26293, 261082, 2.0),
(28477, 261083, 2.0),
(29984, 261084, 1.5),
(32475, 261085, 25.0),
(28597, 261086, 1.5),
(32361, 261087, 25.0),
(32517, 261088, 25.0),
(26841, 261089, 1.2),
(33776, 261090, 25.0),
(38453, 261091, 25.0),
(24812, 261092, 25.0),
(28684, 261093, 12.0),
(27483, 261094, 12.0),
(27977, 261095, 12.0),
(28921, 261096, 10.0),
(26723, 261097, 10.0),
(28587, 261098, 10.0),
(29120, 261099, 8.0),
(27656, 261100, 8.0),
(28923, 261101, 8.0),
(31125, 261102, 10.0),
(33186, 261103, 10.0),
(16028, 261104, 10.0),
(15989, 261105, 8.0),
(28859, 261106, 8.0),
(36853, 261107, 8.0),
(36597, 261108, 6.0),
(33288, 261109, 6.0),
(15990, 261110, 6.0);
-- a temporary table can be named only once per query: the copies come from the base one
CREATE TEMPORARY TABLE `xorwow_tcg_drop` SELECT * FROM `xorwow_tcg_drop_base`;
INSERT INTO `xorwow_tcg_drop` (`creature`, `item`, `chance`) SELECT ct.`difficulty_entry_1`, d.`item`, d.`chance` FROM `xorwow_tcg_drop_base` d JOIN `creature_template` ct ON ct.`entry` = d.`creature` WHERE ct.`difficulty_entry_1` <> 0;
INSERT INTO `xorwow_tcg_drop` (`creature`, `item`, `chance`) SELECT ct.`difficulty_entry_2`, d.`item`, d.`chance` FROM `xorwow_tcg_drop_base` d JOIN `creature_template` ct ON ct.`entry` = d.`creature` WHERE ct.`difficulty_entry_2` <> 0;
INSERT INTO `xorwow_tcg_drop` (`creature`, `item`, `chance`) SELECT ct.`difficulty_entry_3`, d.`item`, d.`chance` FROM `xorwow_tcg_drop_base` d JOIN `creature_template` ct ON ct.`entry` = d.`creature` WHERE ct.`difficulty_entry_3` <> 0;
UPDATE `creature_template` ct JOIN `xorwow_tcg_drop` d ON d.`creature` = ct.`entry` SET ct.`lootid` = ct.`entry` WHERE ct.`lootid` = 0;
DELETE FROM `creature_loot_template` WHERE `Item` BETWEEN 261001 AND 261999;
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`)
    SELECT DISTINCT ct.`lootid`, d.`item`, 0, d.`chance`, 0, 1, 0, 1, 1, 'XorWoW TCG card'
    FROM `xorwow_tcg_drop` d JOIN `creature_template` ct ON ct.`entry` = d.`creature` WHERE ct.`lootid` <> 0;
DROP TEMPORARY TABLE `xorwow_tcg_drop`;
DROP TEMPORARY TABLE `xorwow_tcg_drop_base`;
