/*
 * XorWoW TCG: a card game between two players, played on a 3x3 board drawn by the XorWoW addon.
 * The server is the referee: it owns every account's cards, deck and record, checks the challenges,
 * plays the rules and moves the cards bet between the players. The addon only draws and sends moves.
 *
 * Cards: the world table xorwow_tcg_card (generated by scripts\client-patch\build_tcg.py); card N
 * drops as item 261000+N, whose use spell (261000) adds it to the account's collection. A card
 * counts once its expansion is open (the level cap: 60 classic, 70 +tbc, 80 +wotlk).
 *
 * Rules (FF8's Triple Triad rules, renamed): each player plays the 5 cards of the deck saved in
 * the collection window, one card per turn on an empty square. A side higher than the touching
 * side of an enemy card flips it. Always on: Combo (with Same or Plus) and
 * Elemental: 1-3 random squares carry an element, a card of that element gets +1 on every side
 * there, a card of another element -1, a card without one nothing; and a card whose element beats
 * the other's on the circle (Water > Fire > Frost > Earth > Arcane > Holy > Shadow > Nature >
 * Water) gets +1 on the touching side for that comparison. Same and Plus use the printed numbers.
 * Set by the challenger: Open (both hands shown, else the opponent's cards stay face down until
 * played), Same and Plus (all three on by default), Same Wall (the board's edges count as A for
 * Same) and Sudden Death (a draw is replayed, up to 3 times, with the cards each player holds).
 * Stakes, agreed before the game: none, One (the winner takes 1 card of the loser's deck) or Diff
 * (as many as the score difference). A deck is 5 different owned cards, at most one of tier 9-10
 * and at most two of tier 7 or more; a valid deck is needed to challenge and to accept.
 *
 * A player who leaves duel range, dies, teleports, changes zone or logs out during a game loses it
 * (counted as "fled" in the record) and the winner still takes the stakes.
 *
 * Protocol: addon messages, prefix "XorWoW", body "TCG;<command>;...", whispered by the addon to
 * its own player and swallowed here; the answers are addon whispers to the player. The chat hook,
 * the logout and death hooks and the card spell only queue events: everything is done in the
 * world update, on the world thread, so the game state has one owner.
 */

#include "AccountMgr.h"
#include "Chat.h"
#include "Containers.h"
#include "DBCStores.h"
#include "DatabaseEnv.h"
#include "GameTime.h"
#include "Log.h"
#include "ObjectAccessor.h"
#include "Player.h"
#include "Random.h"
#include "ScriptMgr.h"
#include "SpellInfo.h"
#include "SpellMgr.h"
#include "SpellScript.h"
#include "SpellScriptLoader.h"
#include "StringConvert.h"
#include "StringFormat.h"
#include "Tokenize.h"
#include "World.h"
#include "WorldPacket.h"

#include <algorithm>
#include <array>
#include <deque>
#include <map>
#include <mutex>
#include <optional>
#include <set>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace
{
    constexpr char ADDON_PREFIX[] = "XorWoW";
    constexpr uint32 ITEM_BASE = 261000;
    constexpr uint32 DUEL_SPELL = 7266;
    constexpr uint32 MAX_CARD = 255;
    constexpr uint32 HAND = 5;
    constexpr uint32 TURN_SECONDS = 30;
    constexpr uint32 CHALLENGE_SECONDS = 60;
    constexpr uint32 PICK_SECONDS = 45;
    constexpr uint32 HISTORY_SHOWN = 10;
    constexpr uint32 SUDDEN_DEATH_ROUNDS = 3;
    constexpr float RANGE_SLACK = 3.0f;      // a step past duel range is still fine mid-game

    enum Rules : uint32
    {
        RULE_SAME_WALL    = 0x1,
        RULE_SUDDEN_DEATH = 0x2,
        RULE_OPEN         = 0x4,
        RULE_SAME         = 0x8,
        RULE_PLUS         = 0x10,
        RULE_ALL          = RULE_SAME_WALL | RULE_SUDDEN_DEATH | RULE_OPEN | RULE_SAME | RULE_PLUS,
    };

    enum Stake : uint32
    {
        STAKE_NONE = 0,
        STAKE_ONE  = 1,
        STAKE_DIFF = 2,
    };

    enum Result : uint8
    {
        RESULT_LOSS = 0,
        RESULT_WIN = 1,
        RESULT_DRAW = 2,
        RESULT_FLED = 3,
        RESULT_OPPONENT_FLED = 4,
    };

    struct Card
    {
        uint32 id = 0;
        std::string name;
        uint32 tier = 0;
        uint32 era = 0;
        std::array<uint8, 4> ranks{};   // top, right, bottom, left
        uint8 element = 0;              // 1-8 in circle order, 0 none
    };

    std::vector<Card> cards;            // by id; cards[0] unused
    float duelRange = 10.0f;

    Card const* GetCard(uint32 id)
    {
        return id && id < cards.size() && cards[id].id ? &cards[id] : nullptr;
    }

    uint32 OpenEra()
    {
        uint32 cap = sWorld->getIntConfig(CONFIG_MAX_PLAYER_LEVEL);
        return cap >= 80 ? 2 : cap >= 70 ? 1 : 0;
    }

    // An element beats the next one round the circle.
    bool Beats(uint8 a, uint8 b)
    {
        return a && b && (a % 8) + 1 == b;
    }

    // --- accounts ---------------------------------------------------------------------------------

    struct Account
    {
        std::array<uint16, MAX_CARD + 1> counts{};
        std::array<uint32, HAND> deck{};
        uint32 wins = 0, losses = 0, draws = 0, fled = 0, cardsWon = 0, cardsLost = 0;
    };

    std::unordered_map<uint32, Account> accounts;

    std::string DeckString(Account const& a)
    {
        std::string s;
        for (uint32 i = 0; i < HAND; ++i)
            s += (i ? "," : "") + std::to_string(a.deck[i]);
        return s;
    }

    void SaveAccount(uint32 accountId, Account const& a)
    {
        CharacterDatabase.DirectExecute("REPLACE INTO `xorwow_tcg_account` (`account`, `deck`, `wins`, `losses`, `draws`, `fled`, `cards_won`, `cards_lost`) "
            "VALUES ({}, '{}', {}, {}, {}, {}, {}, {})", accountId, DeckString(a), a.wins, a.losses, a.draws, a.fled, a.cardsWon, a.cardsLost);
    }

    void SaveCount(uint32 accountId, Account const& a, uint32 card)
    {
        if (a.counts[card])
            CharacterDatabase.DirectExecute("REPLACE INTO `xorwow_tcg_collection` (`account`, `card`, `count`) VALUES ({}, {}, {})", accountId, card, a.counts[card]);
        else
            CharacterDatabase.DirectExecute("DELETE FROM `xorwow_tcg_collection` WHERE `account` = {} AND `card` = {}", accountId, card);
    }

    // Empties the deck slots of cards the account no longer owns; true when one was emptied.
    bool PruneDeck(Account& a)
    {
        bool pruned = false;
        for (uint32& id : a.deck)
            if (id && (id > MAX_CARD || !a.counts[id]))
            {
                id = 0;
                pruned = true;
            }
        return pruned;
    }

    // Loads the account the first time it is needed. A new account gets the starter deck: every
    // classic tier 1 card, saved as its deck, so it can play at once.
    Account& GetAccount(uint32 accountId, bool* starter = nullptr)
    {
        auto itr = accounts.find(accountId);
        if (itr != accounts.end())
            return itr->second;

        Account& a = accounts[accountId];
        if (QueryResult result = CharacterDatabase.Query("SELECT `card`, `count` FROM `xorwow_tcg_collection` WHERE `account` = {}", accountId))
        {
            do
            {
                uint32 card = (*result)[0].Get<uint32>();
                if (card <= MAX_CARD)
                    a.counts[card] = (*result)[1].Get<uint16>();
            } while (result->NextRow());
        }

        if (QueryResult result = CharacterDatabase.Query("SELECT `deck`, `wins`, `losses`, `draws`, `fled`, `cards_won`, `cards_lost` "
            "FROM `xorwow_tcg_account` WHERE `account` = {}", accountId))
        {
            Field* f = result->Fetch();
            uint32 i = 0;
            std::string deck = f[0].Get<std::string>();
            for (std::string_view id : Acore::Tokenize(deck, ',', false))
                if (i < HAND)
                    a.deck[i++] = Acore::StringTo<uint32>(id).value_or(0);
            a.wins = f[1].Get<uint32>();
            a.losses = f[2].Get<uint32>();
            a.draws = f[3].Get<uint32>();
            a.fled = f[4].Get<uint32>();
            a.cardsWon = f[5].Get<uint32>();
            a.cardsLost = f[6].Get<uint32>();
            // a deck saved before lost cards left it
            if (PruneDeck(a))
                SaveAccount(accountId, a);
        }
        else
        {
            uint32 i = 0;
            for (Card const& card : cards)
            {
                if (!card.id || card.tier != 1 || card.era != 0)
                    continue;
                a.counts[card.id] += 1;
                SaveCount(accountId, a, card.id);
                if (i < HAND)
                    a.deck[i++] = card.id;
            }
            SaveAccount(accountId, a);
            if (starter)
                *starter = true;
        }
        return a;
    }

    // Why a deck cannot be played, or "" when it can.
    std::string DeckProblem(Account const& a, std::array<uint32, HAND> const& deck)
    {
        uint32 top = 0, high = 0;
        for (uint32 i = 0; i < HAND; ++i)
        {
            Card const* card = GetCard(deck[i]);
            if (!card)
                return "Your deck needs 5 cards.";
            if (card->era > OpenEra())
                return Acore::StringFormat("{} is not in play yet.", card->name);
            if (!a.counts[card->id])
                return Acore::StringFormat("You no longer own {}.", card->name);
            for (uint32 j = 0; j < i; ++j)
                if (deck[j] == deck[i])
                    return "A deck holds 5 different cards.";
            top += card->tier >= 9;
            high += card->tier >= 7;
        }
        if (top > 1)
            return "A deck holds at most one card of tier 9 or 10.";
        if (high > 2)
            return "A deck holds at most two cards of tier 7 or more.";
        return "";
    }

    // The deck's average tier, times 10 (64 = 6.4).
    uint32 DeckStrength(std::array<uint32, HAND> const& deck)
    {
        uint32 sum = 0;
        for (uint32 id : deck)
            if (Card const* card = GetCard(id))
                sum += card->tier;
        return sum * 10 / HAND;
    }

    // --- messages ---------------------------------------------------------------------------------

    void Send(Player* player, std::string const& body)
    {
        if (!player)
            return;
        WorldPacket data;
        ChatHandler::BuildChatPacket(data, CHAT_MSG_WHISPER, LANG_ADDON, player, player, Acore::StringFormat("{}\tTCG;{}", ADDON_PREFIX, body));
        player->SendDirectMessage(&data);
    }

    void Notice(Player* player, std::string const& text)
    {
        if (player)
            ChatHandler(player->GetSession()).SendSysMessage(Acore::StringFormat("|cffe8c46eXorWoW TCG:|r {}", text));
    }

    void SendError(Player* player, std::string const& text)
    {
        Send(player, "ERR;" + text);
    }

    void SendCollection(Player* player, Account const& a)
    {
        std::string body = "COLL;R;";
        bool any = false;
        for (uint32 id = 1; id <= MAX_CARD; ++id)
        {
            if (!a.counts[id])
                continue;
            std::string item = Acore::StringFormat("{}:{}", id, a.counts[id]);
            if (body.size() + item.size() + 1 > 230)
            {
                Send(player, body);
                body = "COLL;+;";
                any = false;
            }
            body += (any ? "," : "") + item;
            any = true;
        }
        Send(player, body);
        Send(player, "COLL;E;");
    }

    void SendCard(Player* player, Account const& a, uint32 card)
    {
        Send(player, Acore::StringFormat("CARD;{};{}", card, a.counts[card]));
    }

    void SendDeck(Player* player, Account const& a)
    {
        std::string problem = DeckProblem(a, a.deck);
        Send(player, Acore::StringFormat("DECK;{};{};{};{}", DeckString(a), problem.empty() ? 1 : 0, DeckStrength(a.deck), problem));
    }

    void SendStats(Player* player, uint32 accountId, Account const& a)
    {
        Send(player, Acore::StringFormat("STATS;{};{};{};{};{};{}", a.wins, a.losses, a.draws, a.fled, a.cardsWon, a.cardsLost));
        Send(player, "HIST;R");
        uint32 now = uint32(GameTime::GetGameTime().count());
        if (QueryResult result = CharacterDatabase.Query("SELECT `opponent`, `result`, `score`, `opponent_score`, `stakes`, `place`, `time` "
            "FROM `xorwow_tcg_history` WHERE `account` = {} ORDER BY `id` DESC LIMIT {}", accountId, HISTORY_SHOWN))
        {
            do
            {
                Field* f = result->Fetch();
                uint32 when = f[6].Get<uint32>();
                Send(player, Acore::StringFormat("HIST;{};{};{};{};{};{};{}", f[0].Get<std::string>(), f[1].Get<uint32>(), f[2].Get<uint32>(),
                    f[3].Get<uint32>(), f[4].Get<std::string>(), f[5].Get<std::string>(), now > when ? now - when : 0));
            } while (result->NextRow());
        }
    }

    // --- games ------------------------------------------------------------------------------------

    struct Seat
    {
        ObjectGuid guid;
        uint32 account = 0;
        std::string name;
        std::array<uint32, HAND> deck{};     // the deck it came with: what a bet takes from
        std::vector<uint32> hand;            // the round's hand, played cards set to 0
        float x = 0.0f, y = 0.0f, z = 0.0f;  // where it stood when the game began
    };

    struct Cell
    {
        uint32 card = 0;
        uint8 seat = 0;
        int8 squareMod = 0;
    };

    enum class Phase { Playing, Picking };

    struct Game
    {
        uint32 id = 0;
        std::array<Seat, 2> seats;
        uint32 rules = 0;
        uint32 stake = STAKE_NONE;
        std::array<Cell, 9> board{};
        std::array<uint8, 9> squares{};      // element of each square, 0 none
        uint8 turn = 0;
        uint8 first = 0;
        uint32 placed = 0;
        uint32 round = 1;
        time_t deadline = 0;
        uint32 mapId = 0, zoneId = 0, instanceId = 0;
        std::string place;
        Phase phase = Phase::Playing;
        uint8 winner = 0;
        uint32 picksLeft = 0;
        std::vector<uint32> pickable;        // the loser's deck cards still to pick from
        std::vector<uint32> taken;
        std::array<Result, 2> results{};
        std::array<uint32, 2> scores{};
    };

    struct Challenge
    {
        uint32 id = 0;
        ObjectGuid from, to;
        uint32 rules = 0;
        uint32 stake = STAKE_NONE;
        time_t expires = 0;
    };

    std::map<uint32, Game> games;
    std::map<uint32, Challenge> challenges;
    std::unordered_map<ObjectGuid, uint32> playerGame;     // the game a player is in
    std::unordered_set<ObjectGuid> withAddon;              // players whose addon said hello
    uint32 nextId = 1;

    time_t Now()
    {
        return GameTime::GetGameTime().count();
    }

    std::string HandString(std::vector<uint32> const& hand)
    {
        std::string s;
        for (size_t i = 0; i < hand.size(); ++i)
            s += (i ? "," : "") + std::to_string(hand[i]);
        return s;
    }

    std::string SquaresString(Game const& g)
    {
        std::string s;
        for (uint32 c = 0; c < 9; ++c)
            if (g.squares[c])
                s += (s.empty() ? "" : ",") + Acore::StringFormat("{}:{}", c + 1, g.squares[c]);
        return s;
    }

    Player* SeatPlayer(Game const& g, uint8 seat)
    {
        return ObjectAccessor::FindConnectedPlayer(g.seats[seat].guid);
    }

    void SendBoth(Game const& g, std::string const& body)
    {
        Send(SeatPlayer(g, 0), body);
        Send(SeatPlayer(g, 1), body);
    }

    // Why the player cannot start a game now, or "".
    std::string Unavailable(Player* player)
    {
        if (!player || !player->IsInWorld())
            return "is not here";
        if (player->GetSession()->IsBot())
            return "is a bot: XorWoW TCG is for players";
        if (!withAddon.count(player->GetGUID()))
            return "does not have the XorWoW addon";
        if (playerGame.count(player->GetGUID()))
            return "is already in a game";
        if (!player->IsAlive())
            return "is dead";
        if (player->IsInCombat())
            return "is in combat";
        if (player->InBattleground() || player->InArena())
            return "is in a battleground";
        return "";
    }

    bool InRange(Player* a, Player* b, float slack)
    {
        return a->GetMapId() == b->GetMapId() && a->GetInstanceId() == b->GetInstanceId() && a->GetDistance(b) <= duelRange + slack;
    }

    void StartRound(Game& g)
    {
        g.board = {};
        g.squares = {};
        g.placed = 0;
        uint32 count = urand(1, 3);
        std::vector<uint32> cells = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
        Acore::Containers::RandomShuffle(cells);
        for (uint32 i = 0; i < count; ++i)
            g.squares[cells[i]] = uint8(urand(1, 8));
        g.first = uint8(urand(0, 1));
        g.turn = g.first;
        g.deadline = Now() + TURN_SECONDS;

        for (uint8 s = 0; s < 2; ++s)
        {
            // without Open, the opponent's cards go out face down ("?") until played
            std::array<std::string, 2> hands = { HandString(g.seats[0].hand), HandString(g.seats[1].hand) };
            if (!(g.rules & RULE_OPEN))
            {
                hands[1 - s].clear();
                for (size_t i = 0; i < g.seats[1 - s].hand.size(); ++i)
                    hands[1 - s] += i ? ",?" : "?";
            }
            Send(SeatPlayer(g, s), Acore::StringFormat("START;{};{};{};{};{};{};{};{};{};{}", g.id, g.seats[1 - s].name, g.rules, g.stake, s,
                hands[0], hands[1], SquaresString(g), g.first, g.round));
        }
        SendBoth(g, Acore::StringFormat("TURN;{};{};{}", g.id, g.turn, TURN_SECONDS));
    }

    uint8 Value(Game const& g, uint32 cell, uint32 side)
    {
        Card const* card = GetCard(g.board[cell].card);
        int v = int(card->ranks[side]) + g.board[cell].squareMod;
        return uint8(std::clamp(v, 1, 10));
    }

    int Neighbour(uint32 cell, uint32 side)
    {
        uint32 row = cell / 3, col = cell % 3;
        switch (side)
        {
            case 0: return row > 0 ? int(cell - 3) : -1;
            case 1: return col < 2 ? int(cell + 1) : -1;
            case 2: return row < 2 ? int(cell + 3) : -1;
            default: return col > 0 ? int(cell - 1) : -1;
        }
    }

    // The plain capture: the card at "from" against each enemy neighbour, counters included.
    void Capture(Game& g, uint32 from, char cause, std::vector<std::string>& events, std::vector<uint32>* flipped)
    {
        uint8 seat = g.board[from].seat;
        Card const* mine = GetCard(g.board[from].card);
        for (uint32 side = 0; side < 4; ++side)
        {
            int n = Neighbour(from, side);
            if (n < 0 || !g.board[n].card || g.board[n].seat == seat)
                continue;
            Card const* theirs = GetCard(g.board[n].card);
            uint32 opposite = (side + 2) % 4;
            int attack = Value(g, from, side), defend = Value(g, n, opposite);
            if (Beats(mine->element, theirs->element))
            {
                ++attack;
                events.push_back(Acore::StringFormat("K:{}:{}", from + 1, side));
            }
            if (Beats(theirs->element, mine->element))
            {
                ++defend;
                events.push_back(Acore::StringFormat("K:{}:{}", n + 1, opposite));
            }
            if (attack > defend)
            {
                g.board[n].seat = seat;
                events.push_back(Acore::StringFormat("F:{}:{}:{}", n + 1, seat, cause));
                if (flipped)
                    flipped->push_back(uint32(n));
            }
        }
    }

    // Places a card and plays out Same, Plus, the captures and the combos. Returns the events the
    // addon animates, in order.
    std::vector<std::string> Place(Game& g, uint8 seat, uint32 handIndex, uint32 cell)
    {
        std::vector<std::string> events;
        uint32 cardId = g.seats[seat].hand[handIndex];
        g.seats[seat].hand[handIndex] = 0;
        Card const* card = GetCard(cardId);
        Cell& c = g.board[cell];
        c.card = cardId;
        c.seat = seat;
        c.squareMod = 0;
        if (g.squares[cell])
        {
            c.squareMod = card->element == g.squares[cell] ? 1 : card->element ? -1 : 0;
            if (c.squareMod)
                events.push_back(Acore::StringFormat("S:{}:{}", cell + 1, c.squareMod));
        }

        // Same and Plus, on the printed numbers
        std::vector<uint32> special;
        std::vector<int> sameHits;
        uint32 sameCount = 0;
        std::map<uint32, std::vector<int>> sums;
        for (uint32 side = 0; side < 4; ++side)
        {
            int n = Neighbour(cell, side);
            uint32 mine = card->ranks[side];
            if (n < 0)
            {
                if ((g.rules & RULE_SAME) && (g.rules & RULE_SAME_WALL) && mine == 10)
                    ++sameCount;
                continue;
            }
            if (!g.board[n].card)
                continue;
            uint32 theirs = GetCard(g.board[n].card)->ranks[(side + 2) % 4];
            if (mine == theirs)
            {
                ++sameCount;
                sameHits.push_back(n);
            }
            sums[mine + theirs].push_back(n);
        }
        auto flip = [&](int n, char cause)
        {
            if (g.board[n].seat == seat)
                return;
            g.board[n].seat = seat;
            events.push_back(Acore::StringFormat("F:{}:{}:{}", n + 1, seat, cause));
            special.push_back(uint32(n));
        };
        if ((g.rules & RULE_SAME) && sameCount >= 2)
            for (int n : sameHits)
                flip(n, 'S');
        if (g.rules & RULE_PLUS)
            for (auto const& [sum, cellsWithSum] : sums)
                if (cellsWithSum.size() >= 2)
                    for (int n : cellsWithSum)
                        flip(n, 'P');

        Capture(g, cell, 'B', events, nullptr);

        // Combo: a card flipped by Same or Plus captures in turn, and so on
        std::deque<uint32> queue(special.begin(), special.end());
        while (!queue.empty())
        {
            uint32 from = queue.front();
            queue.pop_front();
            std::vector<uint32> more;
            Capture(g, from, 'C', events, &more);
            queue.insert(queue.end(), more.begin(), more.end());
        }
        return events;
    }

    void Score(Game const& g, uint32& s0, uint32& s1)
    {
        s0 = s1 = 0;
        for (Cell const& c : g.board)
            if (c.card)
                (c.seat ? s1 : s0) += 1;
        for (uint32 id : g.seats[0].hand)
            s0 += id ? 1 : 0;
        for (uint32 id : g.seats[1].hand)
            s1 += id ? 1 : 0;
    }

    void Release(Game const& g)
    {
        playerGame.erase(g.seats[0].guid);
        playerGame.erase(g.seats[1].guid);
    }

    void CountResult(Game const& g, uint8 seat, Result result)
    {
        Seat const& s = g.seats[seat];
        Account& a = GetAccount(s.account);
        switch (result)
        {
            case RESULT_WIN: case RESULT_OPPONENT_FLED: ++a.wins; break;
            case RESULT_LOSS: ++a.losses; break;
            case RESULT_FLED: ++a.losses; ++a.fled; break;
            default: ++a.draws; break;
        }
        SaveAccount(s.account, a);
    }

    void WriteHistory(Game const& g, uint8 seat, Result result, uint32 mine, uint32 theirs, std::string const& stakes)
    {
        Seat const& s = g.seats[seat];
        std::string opponent = g.seats[1 - seat].name, st = stakes, place = g.place;
        CharacterDatabase.EscapeString(opponent);
        CharacterDatabase.EscapeString(st);
        CharacterDatabase.EscapeString(place);
        CharacterDatabase.DirectExecute("INSERT INTO `xorwow_tcg_history` (`account`, `opponent`, `result`, `score`, `opponent_score`, `stakes`, `place`, `time`) "
            "VALUES ({}, '{}', {}, {}, {}, '{}', '{}', {})", s.account, opponent, uint32(result), mine, theirs, st, place, uint32(Now()));
    }

    std::string StakeName(uint32 stake)
    {
        return stake == STAKE_ONE ? "One" : stake == STAKE_DIFF ? "Diff" : "None";
    }

    void FinishGame(Game& g)
    {
        // the history rows and the stats go out once the bet is settled
        std::string cardsMoved;
        for (uint32 card : g.taken)
            cardsMoved += (cardsMoved.empty() ? "" : ", ") + GetCard(card)->name;
        for (uint8 s = 0; s < 2; ++s)
        {
            std::string stakes = g.stake == STAKE_NONE ? "" : StakeName(g.stake);
            if (!cardsMoved.empty())
                stakes = (s == g.winner ? "Won " : "Lost ") + cardsMoved;
            WriteHistory(g, s, g.results[s], g.scores[s], g.scores[1 - s], stakes);
        }
        for (uint8 s = 0; s < 2; ++s)
            if (Player* p = SeatPlayer(g, s))
                SendStats(p, g.seats[s].account, GetAccount(g.seats[s].account));
        Release(g);
        uint32 id = g.id;   // g is the map's element: erase by a copy of its key
        games.erase(id);
    }

    // Moves one card of the loser's deck to the winner.
    void Take(Game& g, uint32 card)
    {
        auto itr = std::find(g.pickable.begin(), g.pickable.end(), card);
        if (itr == g.pickable.end())
            return;
        g.pickable.erase(itr);
        Seat const& win = g.seats[g.winner];
        Seat const& lose = g.seats[1 - g.winner];
        Account& wa = GetAccount(win.account);
        Account& la = GetAccount(lose.account);
        --g.picksLeft;
        if (!la.counts[card])
            return;   // gone already (cannot happen while the game holds it, but stay safe)
        --la.counts[card];
        ++wa.counts[card];
        ++wa.cardsWon;
        ++la.cardsLost;
        PruneDeck(la);   // the last copy leaves the deck too
        g.taken.push_back(card);
        SaveCount(lose.account, la, card);
        SaveCount(win.account, wa, card);
        SaveAccount(lose.account, la);
        SaveAccount(win.account, wa);
        Player* wp = SeatPlayer(g, g.winner);
        Player* lp = SeatPlayer(g, 1 - g.winner);
        SendCard(wp, wa, card);
        SendCard(lp, la, card);
        SendBoth(g, Acore::StringFormat("TAKEN;{};{};{}", g.id, g.winner, card));
        Card const* c = GetCard(card);
        Notice(wp, Acore::StringFormat("You won {} from {}.", c->name, lose.name));
        Notice(lp, Acore::StringFormat("{} took your {}.", win.name, c->name));
        if (lp)
            SendDeck(lp, la);
    }

    void EndPicking(Game& g)
    {
        SendBoth(g, Acore::StringFormat("PICKED;{}", g.id));
        FinishGame(g);
    }

    // The game is over: the record, then the bet.
    void EndGame(Game& g, int winner, int fledSeat, std::string const& why = "")
    {
        uint32 s0, s1;
        Score(g, s0, s1);
        std::array<uint32, 2> score = { s0, s1 };
        for (uint8 s = 0; s < 2; ++s)
        {
            Result r = winner < 0 ? RESULT_DRAW : (winner == s ? (fledSeat >= 0 ? RESULT_OPPONENT_FLED : RESULT_WIN)
                                                                : (fledSeat == s ? RESULT_FLED : RESULT_LOSS));
            g.results[s] = r;
            g.scores[s] = score[s];
            CountResult(g, s, r);
            Send(SeatPlayer(g, s), Acore::StringFormat("END;{};{};{};{};{};{};{}", g.id, winner < 0 ? "D" : winner == s ? "W" : "L",
                score[s], score[1 - s], fledSeat < 0 ? "" : g.seats[fledSeat].name, uint32(r), why));
        }

        if (winner < 0 || g.stake == STAKE_NONE)
        {
            FinishGame(g);
            return;
        }
        g.winner = uint8(winner);
        uint32 diff = score[winner] > score[1 - winner] ? score[winner] - score[1 - winner] : 1;
        g.picksLeft = g.stake == STAKE_ONE ? 1 : std::clamp<uint32>(diff, 1, HAND);
        g.pickable.assign(g.seats[1 - winner].deck.begin(), g.seats[1 - winner].deck.end());
        g.phase = Phase::Picking;
        g.deadline = Now() + PICK_SECONDS;
        Send(SeatPlayer(g, uint8(winner)), Acore::StringFormat("PICK;{};{};{};{}", g.id, g.picksLeft, HandString(g.pickable), PICK_SECONDS));
        Send(SeatPlayer(g, uint8(1 - winner)), Acore::StringFormat("PICKWAIT;{};{}", g.id, g.picksLeft));
        if (!SeatPlayer(g, uint8(winner)))
            g.deadline = 0;   // the winner left right away: the server picks
    }

    void AutoPick(Game& g)
    {
        while (g.picksLeft && !g.pickable.empty())
        {
            auto best = std::max_element(g.pickable.begin(), g.pickable.end(),
                [](uint32 a, uint32 b) { return GetCard(a)->tier < GetCard(b)->tier; });
            Take(g, *best);
        }
        EndPicking(g);
    }

    void Fled(Game& g, uint8 seat, std::string const& why)
    {
        if (g.phase != Phase::Playing)
            return;
        Notice(SeatPlayer(g, 1 - seat), Acore::StringFormat("{} {}: you win.", g.seats[seat].name, why));
        Notice(SeatPlayer(g, seat), Acore::StringFormat("You {}: you lose the game.", why));
        EndGame(g, 1 - seat, seat, why);
    }

    void EndOfRound(Game& g)
    {
        uint32 s0, s1;
        Score(g, s0, s1);
        if (s0 == s1 && (g.rules & RULE_SUDDEN_DEATH) && g.round < SUDDEN_DEATH_ROUNDS + 1)
        {
            // Sudden Death: each player's new hand is the cards of its colour
            std::array<std::vector<uint32>, 2> hands;
            for (Cell const& c : g.board)
                hands[c.seat].push_back(c.card);
            for (uint8 s = 0; s < 2; ++s)
                for (uint32 id : g.seats[s].hand)
                    if (id)
                        hands[s].push_back(id);
            g.seats[0].hand = hands[0];
            g.seats[1].hand = hands[1];
            ++g.round;
            SendBoth(g, Acore::StringFormat("SUDDEN;{};{}", g.id, g.round));
            StartRound(g);
            return;
        }
        EndGame(g, s0 == s1 ? -1 : s0 > s1 ? 0 : 1, -1);
    }

    void Play(Game& g, uint8 seat, uint32 handIndex, uint32 cell)
    {
        std::vector<std::string> events = Place(g, seat, handIndex, cell);
        std::string ev;
        for (std::string const& e : events)
            ev += (ev.empty() ? "" : ",") + e;
        SendBoth(g, Acore::StringFormat("MOVE;{};{};{};{};{};{}", g.id, seat, handIndex + 1, g.board[cell].card, cell + 1, ev));
        ++g.placed;
        if (g.placed >= 9)
        {
            EndOfRound(g);
            return;
        }
        g.turn = uint8(1 - seat);
        g.deadline = Now() + TURN_SECONDS;
        SendBoth(g, Acore::StringFormat("TURN;{};{};{}", g.id, g.turn, TURN_SECONDS));
    }

    // Out of time: a random card on a random empty square.
    void AutoPlay(Game& g)
    {
        std::vector<uint32> hand, empty;
        for (uint32 i = 0; i < g.seats[g.turn].hand.size(); ++i)
            if (g.seats[g.turn].hand[i])
                hand.push_back(i);
        for (uint32 c = 0; c < 9; ++c)
            if (!g.board[c].card)
                empty.push_back(c);
        if (hand.empty() || empty.empty())
            return;
        Notice(SeatPlayer(g, g.turn), "Out of time: a card was played for you.");
        Play(g, g.turn, Acore::Containers::SelectRandomContainerElement(hand), Acore::Containers::SelectRandomContainerElement(empty));
    }

    std::string ZoneName(uint32 zoneId)
    {
        AreaTableEntry const* area = sAreaTableStore.LookupEntry(zoneId);
        return area ? area->area_name[0] : "";
    }

    // --- commands from the addon ------------------------------------------------------------------

    void HandleHello(Player* player)
    {
        uint32 accountId = player->GetSession()->GetAccountId();
        withAddon.insert(player->GetGUID());
        bool starter = false;
        Account& a = GetAccount(accountId, &starter);
        Send(player, Acore::StringFormat("ERAS;{};{}", OpenEra(), uint32(duelRange)));
        SendCollection(player, a);
        SendDeck(player, a);
        SendStats(player, accountId, a);
        if (starter)
            Notice(player, "Welcome to XorWoW TCG! Your starter deck is ready: open the collection from the minimap button.");
    }

    void HandleDeck(Player* player, std::vector<std::string_view> const& args)
    {
        if (playerGame.count(player->GetGUID()))
            return SendError(player, "You cannot change your deck during a game.");
        uint32 accountId = player->GetSession()->GetAccountId();
        Account& a = GetAccount(accountId);
        std::array<uint32, HAND> deck{};
        uint32 i = 0;
        if (args.size() > 1)
            for (std::string_view id : Acore::Tokenize(args[1], ',', false))
                if (i < HAND)
                    deck[i++] = Acore::StringTo<uint32>(id).value_or(0);
        // an incomplete deck is saved too (the window keeps the player's picks), it just cannot play
        for (uint32 j = 0; j < HAND; ++j)
            if (deck[j] && (!GetCard(deck[j]) || !a.counts[deck[j]]))
                deck[j] = 0;
        a.deck = deck;
        SaveAccount(accountId, a);
        SendDeck(player, a);
    }

    void HandleChallenge(Player* player, std::vector<std::string_view> const& args)
    {
        if (args.size() < 4)
            return;
        std::string why = Unavailable(player);
        if (!why.empty())
            return SendError(player, "You cannot start a game now (" + player->GetName() + " " + why + ").");
        for (auto const& [id, c] : challenges)
            if (c.from == player->GetGUID() || c.to == player->GetGUID())
                return SendError(player, "You already have a challenge waiting.");
        Account& mine = GetAccount(player->GetSession()->GetAccountId());
        std::string problem = DeckProblem(mine, mine.deck);
        if (!problem.empty())
            return SendError(player, problem + " Fix your deck in the collection window first.");

        Player* target = ObjectAccessor::FindPlayerByName(std::string(args[1]), true);
        if (!target || target == player)
            return SendError(player, "Target another player to challenge them.");
        why = Unavailable(target);
        if (!why.empty())
            return SendError(player, target->GetName() + " " + why + ".");
        if (!InRange(player, target, 0.0f))
            return SendError(player, Acore::StringFormat("{} is too far: come within {} yards, like for a duel.", target->GetName(), uint32(duelRange)));
        for (auto const& [id, c] : challenges)
            if (c.from == target->GetGUID() || c.to == target->GetGUID())
                return SendError(player, target->GetName() + " is answering another challenge.");
        Account& theirs = GetAccount(target->GetSession()->GetAccountId());
        if (!DeckProblem(theirs, theirs.deck).empty())
            return SendError(player, target->GetName() + " does not have a valid deck.");

        Challenge c;
        c.id = nextId++;
        c.from = player->GetGUID();
        c.to = target->GetGUID();
        c.rules = Acore::StringTo<uint32>(args[2]).value_or(0) & RULE_ALL;
        c.stake = std::min<uint32>(Acore::StringTo<uint32>(args[3]).value_or(0), STAKE_DIFF);
        c.expires = Now() + CHALLENGE_SECONDS;
        challenges[c.id] = c;
        Send(player, Acore::StringFormat("SENT;{};{};{};{};{}", c.id, target->GetName(), c.rules, c.stake, CHALLENGE_SECONDS));
        Send(target, Acore::StringFormat("CHALLENGED;{};{};{};{};{};{};{}", c.id, player->GetName(), c.rules, c.stake,
            DeckStrength(mine.deck), DeckStrength(theirs.deck), CHALLENGE_SECONDS));
    }

    void CloseChallenge(Challenge const& c, std::string const& why)
    {
        Send(ObjectAccessor::FindConnectedPlayer(c.from), Acore::StringFormat("CLOSED;{};{}", c.id, why));
        Send(ObjectAccessor::FindConnectedPlayer(c.to), Acore::StringFormat("CLOSED;{};{}", c.id, why));
        uint32 id = c.id;   // c may be the map's element: erase by a copy of its key
        challenges.erase(id);
    }

    void HandleAnswer(Player* player, std::vector<std::string_view> const& args, bool accept)
    {
        if (args.size() < 2)
            return;
        uint32 id = Acore::StringTo<uint32>(args[1]).value_or(0);
        auto itr = challenges.find(id);
        if (itr == challenges.end())
            return;
        Challenge c = itr->second;
        if (c.from == player->GetGUID() && !accept)
            return CloseChallenge(c, "withdrawn");
        if (c.to != player->GetGUID())
            return;
        Player* from = ObjectAccessor::FindConnectedPlayer(c.from);
        if (!accept)
            return CloseChallenge(c, player->GetName() + " declined");

        std::string why = Unavailable(from);
        if (!why.empty())
            return CloseChallenge(c, (from ? from->GetName() : "The challenger") + " " + why);
        why = Unavailable(player);
        if (!why.empty())
            return CloseChallenge(c, player->GetName() + " " + why);
        if (!InRange(from, player, RANGE_SLACK))
            return CloseChallenge(c, "too far apart");
        Account& fa = GetAccount(from->GetSession()->GetAccountId());
        Account& ta = GetAccount(player->GetSession()->GetAccountId());
        if (!DeckProblem(fa, fa.deck).empty() || !DeckProblem(ta, ta.deck).empty())
            return CloseChallenge(c, "a deck is no longer valid");
        challenges.erase(id);

        Game g;
        g.id = id;
        g.rules = c.rules;
        g.stake = c.stake;
        Player* players[2] = { from, player };
        Account* accs[2] = { &fa, &ta };
        for (uint8 s = 0; s < 2; ++s)
        {
            Seat& seat = g.seats[s];
            seat.guid = players[s]->GetGUID();
            seat.account = players[s]->GetSession()->GetAccountId();
            seat.name = players[s]->GetName();
            seat.deck = accs[s]->deck;
            seat.hand.assign(seat.deck.begin(), seat.deck.end());
            players[s]->GetPosition(seat.x, seat.y, seat.z);
            playerGame[seat.guid] = g.id;
        }
        g.mapId = from->GetMapId();
        g.instanceId = from->GetInstanceId();
        g.zoneId = from->GetZoneId();
        g.place = ZoneName(g.zoneId);
        games[g.id] = g;
        StartRound(games[g.id]);
    }

    void HandlePlay(Player* player, std::vector<std::string_view> const& args)
    {
        if (args.size() < 4)
            return;
        auto itr = games.find(Acore::StringTo<uint32>(args[1]).value_or(0));
        if (itr == games.end() || itr->second.phase != Phase::Playing)
            return;
        Game& g = itr->second;
        uint8 seat = g.seats[0].guid == player->GetGUID() ? 0 : g.seats[1].guid == player->GetGUID() ? 1 : 2;
        if (seat != g.turn)
            return SendError(player, "It is not your turn.");
        uint32 handIndex = Acore::StringTo<uint32>(args[2]).value_or(0);
        uint32 cell = Acore::StringTo<uint32>(args[3]).value_or(0);
        if (!handIndex || handIndex > g.seats[seat].hand.size() || !g.seats[seat].hand[handIndex - 1] || !cell || cell > 9 || g.board[cell - 1].card)
            return SendError(player, "You cannot play there.");
        Play(g, seat, handIndex - 1, cell - 1);
    }

    void HandlePick(Player* player, std::vector<std::string_view> const& args)
    {
        if (args.size() < 3)
            return;
        auto itr = games.find(Acore::StringTo<uint32>(args[1]).value_or(0));
        if (itr == games.end() || itr->second.phase != Phase::Picking)
            return;
        Game& g = itr->second;
        if (g.seats[g.winner].guid != player->GetGUID())
            return;
        Take(g, Acore::StringTo<uint32>(args[2]).value_or(0));
        if (!g.picksLeft || g.pickable.empty())
            EndPicking(g);
    }

    void HandleForfeit(Player* player, std::vector<std::string_view> const& args)
    {
        if (args.size() < 2)
            return;
        auto itr = games.find(Acore::StringTo<uint32>(args[1]).value_or(0));
        if (itr == games.end())
            return;
        Game& g = itr->second;
        for (uint8 s = 0; s < 2; ++s)
            if (g.seats[s].guid == player->GetGUID())
            {
                Fled(g, s, "gave up");   // may end and erase the game
                break;
            }
    }

    // A spare copy back into the bags, to trade it.
    void HandleTake(Player* player, std::vector<std::string_view> const& args)
    {
        if (args.size() < 2)
            return;
        uint32 id = Acore::StringTo<uint32>(args[1]).value_or(0);
        Card const* card = GetCard(id);
        uint32 accountId = player->GetSession()->GetAccountId();
        Account& a = GetAccount(accountId);
        if (!card || !a.counts[id])
            return SendError(player, "You have no copy of that card.");
        if (playerGame.count(player->GetGUID()))
            return SendError(player, "Not during a game.");
        if (!player->AddItem(ITEM_BASE + id, 1))
            return SendError(player, "Your bags are full.");
        --a.counts[id];
        SaveCount(accountId, a, id);
        if (PruneDeck(a))
            SaveAccount(accountId, a);
        SendCard(player, a, id);
        SendDeck(player, a);
    }

    // --- the queue -------------------------------------------------------------------------------

    enum class EventType { Command, Logout, Died, CardUsed };

    struct Event
    {
        EventType type;
        ObjectGuid guid;
        std::string text;
        uint32 card = 0;
    };

    std::mutex queueLock;
    std::vector<Event> queue;

    void Push(Event e)
    {
        std::lock_guard<std::mutex> guard(queueLock);
        queue.push_back(std::move(e));
    }

    void HandleCommand(Player* player, std::string const& text)
    {
        std::vector<std::string_view> args = Acore::Tokenize(text, ';', true);
        if (args.empty())
            return;
        std::string_view cmd = args[0];
        if (cmd == "HELLO")
            HandleHello(player);
        else if (!withAddon.count(player->GetGUID()))
            return;
        else if (cmd == "DECK")
            HandleDeck(player, args);
        else if (cmd == "CHAL")
            HandleChallenge(player, args);
        else if (cmd == "ACCEPT")
            HandleAnswer(player, args, true);
        else if (cmd == "DECLINE")
            HandleAnswer(player, args, false);
        else if (cmd == "PLAY")
            HandlePlay(player, args);
        else if (cmd == "PICK")
            HandlePick(player, args);
        else if (cmd == "FORFEIT")
            HandleForfeit(player, args);
        else if (cmd == "TAKE")
            HandleTake(player, args);
        else if (cmd == "STATS")
            SendStats(player, player->GetSession()->GetAccountId(), GetAccount(player->GetSession()->GetAccountId()));
    }

    void LeaveAll(ObjectGuid guid, std::string const& why)
    {
        std::vector<uint32> closing;
        for (auto const& [id, c] : challenges)
            if (c.from == guid || c.to == guid)
                closing.push_back(id);
        for (uint32 id : closing)
            CloseChallenge(challenges[id], why);
        auto itr = playerGame.find(guid);
        if (itr != playerGame.end())
        {
            auto g = games.find(itr->second);
            if (g != games.end())
                for (uint8 s = 0; s < 2; ++s)
                    if (g->second.seats[s].guid == guid)
                    {
                        Fled(g->second, s, why);   // may end and erase the game
                        break;
                    }
        }
    }

    void ProcessQueue()
    {
        std::vector<Event> events;
        {
            std::lock_guard<std::mutex> guard(queueLock);
            events.swap(queue);
        }
        for (Event const& e : events)
        {
            switch (e.type)
            {
                case EventType::Command:
                    if (Player* p = ObjectAccessor::FindConnectedPlayer(e.guid))
                        HandleCommand(p, e.text);
                    break;
                case EventType::Logout:
                    LeaveAll(e.guid, "logged out");
                    withAddon.erase(e.guid);
                    break;
                case EventType::Died:
                    LeaveAll(e.guid, "died");
                    break;
                case EventType::CardUsed:
                {
                    Player* p = ObjectAccessor::FindConnectedPlayer(e.guid);
                    Card const* card = GetCard(e.card);
                    if (!p || !card)
                        break;
                    uint32 accountId = p->GetSession()->GetAccountId();
                    Account& a = GetAccount(accountId);
                    ++a.counts[card->id];
                    SaveCount(accountId, a, card->id);
                    SendCard(p, a, card->id);
                    Notice(p, Acore::StringFormat("{} added to your collection ({} owned).", card->name, a.counts[card->id]));
                    break;
                }
            }
        }
    }

    // The players' positions, the turn and pick clocks, the challenges' expiry.
    void Tick()
    {
        time_t now = Now();
        std::vector<uint32> expired;
        for (auto const& [id, c] : challenges)
            if (now >= c.expires)
                expired.push_back(id);
        for (uint32 id : expired)
            CloseChallenge(challenges[id], "no answer");

        std::vector<uint32> ids;
        for (auto const& [id, g] : games)
            ids.push_back(id);
        for (uint32 id : ids)
        {
            auto itr = games.find(id);
            if (itr == games.end())
                continue;
            Game& g = itr->second;
            if (g.phase == Phase::Playing)
            {
                Player* p[2] = { SeatPlayer(g, 0), SeatPlayer(g, 1) };
                // Out of range: the one who moved farther from where it stood walked away, not seat 0
                int walker = -1;
                if (p[0] && p[0]->IsInWorld() && p[1] && p[1]->IsInWorld() && p[0]->GetMapId() == p[1]->GetMapId()
                    && p[0]->GetInstanceId() == p[1]->GetInstanceId() && !InRange(p[0], p[1], RANGE_SLACK))
                    walker = p[0]->GetExactDist(g.seats[0].x, g.seats[0].y, g.seats[0].z)
                        >= p[1]->GetExactDist(g.seats[1].x, g.seats[1].y, g.seats[1].z) ? 0 : 1;
                bool ended = false;
                for (uint8 s = 0; s < 2 && !ended; ++s)
                {
                    std::string why;
                    if (!p[s] || !p[s]->IsInWorld())
                        why = p[s] ? "teleported away" : "logged out";
                    else if (!p[s]->IsAlive())
                        why = "died";
                    else if (p[s]->GetMapId() != g.mapId || p[s]->GetInstanceId() != g.instanceId || p[s]->GetZoneId() != g.zoneId)
                        why = "left the zone";
                    else if (walker == s)
                        why = "walked away";
                    if (!why.empty())
                    {
                        Fled(g, s, why);
                        ended = true;
                    }
                }
                if (ended)
                    continue;
                if (now >= g.deadline)
                    AutoPlay(g);
            }
            else if (now >= g.deadline)
                AutoPick(g);
        }
    }

    void LoadCards()
    {
        cards.assign(1, Card{});
        if (QueryResult result = WorldDatabase.Query("SELECT `id`, `name`, `tier`, `era`, `top`, `right`, `bottom`, `left`, `element` FROM `xorwow_tcg_card`"))
        {
            do
            {
                Field* f = result->Fetch();
                Card c;
                c.id = f[0].Get<uint32>();
                if (!c.id || c.id > MAX_CARD)
                    continue;
                c.name = f[1].Get<std::string>();
                c.tier = f[2].Get<uint32>();
                c.era = f[3].Get<uint32>();
                for (uint32 i = 0; i < 4; ++i)
                    c.ranks[i] = uint8(std::clamp<uint32>(f[4 + i].Get<uint32>(), 1, 10));
                c.element = f[8].Get<uint8>();
                if (cards.size() <= c.id)
                    cards.resize(c.id + 1);
                cards[c.id] = c;
            } while (result->NextRow());
        }
        if (SpellInfo const* duel = sSpellMgr->GetSpellInfo(DUEL_SPELL))
            if (float range = std::max(duel->GetMaxRange(true), duel->GetMaxRange(false)))
                duelRange = range;
        LOG_INFO("server.loading", ">> XorWoW TCG: {} cards, duel range {} yards, open up to era {}", cards.size() - 1, duelRange, OpenEra());
    }
}

class xorwow_tcg_playerscript : public PlayerScript
{
public:
    xorwow_tcg_playerscript() : PlayerScript("xorwow_tcg_playerscript",
        { PLAYERHOOK_CAN_PLAYER_USE_PRIVATE_CHAT, PLAYERHOOK_ON_LOGOUT, PLAYERHOOK_ON_PLAYER_JUST_DIED }) { }

    bool OnPlayerCanUseChat(Player* player, uint32 type, uint32 lang, std::string& msg, Player* receiver) override
    {
        if (lang != LANG_ADDON || type != CHAT_MSG_WHISPER || receiver != player)
            return true;
        std::string const prefix = Acore::StringFormat("{}\tTCG;", ADDON_PREFIX);
        if (msg.rfind(prefix, 0) != 0)
            return true;
        Push({ EventType::Command, player->GetGUID(), msg.substr(prefix.size()), 0 });
        return false;
    }

    void OnPlayerLogout(Player* player) override
    {
        Push({ EventType::Logout, player->GetGUID(), "", 0 });
    }

    void OnPlayerJustDied(Player* player) override
    {
        Push({ EventType::Died, player->GetGUID(), "", 0 });
    }
};

class xorwow_tcg_worldscript : public WorldScript
{
public:
    xorwow_tcg_worldscript() : WorldScript("xorwow_tcg_worldscript", { WORLDHOOK_ON_STARTUP, WORLDHOOK_ON_UPDATE }) { }

    void OnStartup() override
    {
        LoadCards();
    }

    void OnUpdate(uint32 diff) override
    {
        ProcessQueue();
        timer += diff;
        if (timer < 250)
            return;
        timer = 0;
        Tick();
    }

private:
    uint32 timer = 0;
};

// The card item's "use": the card goes to the account (the item's charge uses it up).
class spell_xorwow_tcg_card : public SpellScript
{
    PrepareSpellScript(spell_xorwow_tcg_card)

    void RememberCard()
    {
        if (Item* item = GetCastItem())
            card = item->GetEntry() - ITEM_BASE;
    }

    void HandleDummy(SpellEffIndex /*effIndex*/)
    {
        Player* player = GetCaster() ? GetCaster()->ToPlayer() : nullptr;
        if (player && card)
            Push({ EventType::CardUsed, player->GetGUID(), "", card });
    }

    void Register() override
    {
        BeforeCast += SpellCastFn(spell_xorwow_tcg_card::RememberCard);
        OnEffectHitTarget += SpellEffectFn(spell_xorwow_tcg_card::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }

    uint32 card = 0;
};

void AddSC_xorwow_tcg()
{
    new xorwow_tcg_playerscript();
    new xorwow_tcg_worldscript();
    RegisterSpellScript(spell_xorwow_tcg_card);
}
